version: "2"
run:
  concurrency: 4
  tests: false
linters:
  default: none
  enable:
    - dupl
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    errcheck:
      check-type-assertions: true
    gocritic:
      disabled-checks:
        - hugeParam
        - rangeExprCopy
        - rangeValCopy
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    revive:
      severity: warning
      rules:
        - name: package-comments
          severity: warning
          disabled: true
        - name: exported
          arguments:
            - checkPrivateReceivers
            - disableStutteringCheck
          severity: warning
          disabled: false
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl%
        path: (.+)_test.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: false
formatters:
  settings:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
